import Head from 'next/head';
import Header from './header/header';

function Layout({ children }) {
	return (
		<>
			<Head>
				{/* Page Description */}
				<meta name='description' content='Generated by create next app' />
				{/* Favicon */}
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{/* HEADER CONTENT */}
			<Header />

			{/* MAIN CONTENT */}
			<main>{children}</main>
		</>
	);
}

export default Layout;
