import Head from 'next/head'
import Navbar from './navbar'

function Layout({children}) {
  return (
    <>
      <Head>
        {/* Page Description */}
        <meta name="description" content="Generated by create next app" />
        {/* Favicon */}
        <link rel="icon" href="/favicon.ico" />
        {/* Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=Comfortaa:wght@400;700&family=Montserrat:wght@400;700&display=swap" rel="stylesheet"></link>
      </Head>
      <Navbar />
     <main>{children}</main> 
    </>
  )
}

export default Layout;
