import Head from 'next/head';
import Navbar from './navBar/navbar';

function Layout({ children }) {
	return (
		<>
			<Head>
				{/* Page Description */}
				<meta name='description' content='Generated by create next app' />
				{/* Favicon */}
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<main>{children}</main>
		</>
	);
}

export default Layout;
