import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        {/* Title */}
        <title>Nate Valline | Web Developer</title>
        {/* Page Description */}
        <meta name="description" content="Generated by create next app" />
        {/* Favicon */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Nate Valline Portfolio v. 5
        </h1>
      </main>
    </div>
  )
}
